-- Reference lookup tables mirroring the frontend's fixed enum values.
CREATE TABLE
    IF NOT EXISTS departments (id TEXT PRIMARY KEY, label TEXT NOT NULL);

CREATE TABLE
    IF NOT EXISTS factions (id TEXT PRIMARY KEY, label TEXT NOT NULL);

CREATE TABLE
    IF NOT EXISTS kiosks (id TEXT PRIMARY KEY, label TEXT NOT NULL);

-- System administrators and advisers who can access the attendance system.
CREATE TABLE
    IF NOT EXISTS admin_accounts (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        employee_id TEXT NOT NULL UNIQUE,
        password TEXT NOT NULL,
        role TEXT NOT NULL CHECK (role IN ('super-admin', 'admin', 'adviser')),
        scope_type TEXT NOT NULL CHECK (scope_type IN ('global', 'faction', 'custom')),
        scope_faction_id TEXT REFERENCES factions (id),
        scope_label TEXT,
        status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (
            (
                scope_type = 'faction'
                AND scope_faction_id IS NOT NULL
                AND scope_label IS NULL
            )
            OR (
                scope_type = 'custom'
                AND scope_faction_id IS NULL
                AND scope_label IS NOT NULL
            )
            OR (
                scope_type = 'global'
                AND scope_faction_id IS NULL
                AND scope_label IS NULL
            )
        )
    );

-- Student directory: one row per enrolled student/delegate.
CREATE TABLE
    IF NOT EXISTS students (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT UNIQUE,
        photo_url TEXT,
        course TEXT NOT NULL,
        department_id TEXT NOT NULL REFERENCES departments (id),
        faction_id TEXT NOT NULL REFERENCES factions (id),
        status TEXT NOT NULL DEFAULT 'not-logged' CHECK (
            status IN ('checked-in', 'checked-out', 'not-logged')
        ),
        status_time TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- Attendance logs: one row per kiosk scan (time in / time out) for a student.
CREATE TABLE
    IF NOT EXISTS attendance_logs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        scan_ref TEXT NOT NULL UNIQUE,
        student_id TEXT NOT NULL REFERENCES students (id),
        log_type TEXT NOT NULL CHECK (log_type IN ('TIME IN', 'TIME OUT')),
        kiosk_id TEXT NOT NULL REFERENCES kiosks (id),
        user_logged TEXT NOT NULL,
        scan_date TEXT NOT NULL,
        scan_time TEXT NOT NULL,
        verified BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

ALTER TABLE attendance_logs
ADD COLUMN IF NOT EXISTS user_logged TEXT;

UPDATE attendance_logs
SET
    user_logged = kiosk_id
WHERE
    user_logged IS NULL;

ALTER TABLE attendance_logs
ALTER COLUMN user_logged
SET
    NOT NULL;

CREATE INDEX IF NOT EXISTS idx_attendance_logs_student_id ON attendance_logs (student_id);

CREATE INDEX IF NOT EXISTS idx_attendance_logs_scan_date ON attendance_logs (scan_date);